config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  root "homes#chatroom"
  get "chatroom/:room_id", to: "homes#chatroom", as: "chatroom"
  resources :users
  post 'new/message', to: "messages#create", as: "new_message"
  get 'sign_in', to: "sessions#sign_in", as: "sign_in"
  post 'sign_in', to: "sessions#post_sign_in"
  delete 'log_out', to: "sessions#log_out", as: "logout"
  resources :chat_rooms
  get 'join_room/:chat_room_id', to: "chat_rooms#join_room", as: "join_room"
  get '/owner', to: "chat_rooms#owner", as: "owner"
  get 'accept_request/:chat_room_id/:requester_id', to: "chat_rooms#accept_request", as: "accept_request"
  get 'reject_request/:chat_room_id/:requester_id', to: "chat_rooms#reject_request", as: "reject_request"
  get '/see_request/:chat_room_id', to: "chat_rooms#see_request", as: "see_requests"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :room_users
  has_many :room_users
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :chat_room
    validates :body, presence: { message: "Message can't be blank!!" }
end

app/models/request.rb
class Request < ApplicationRecord
  scope :pending, -> {where(request_status:0)}
  scope :accepted, -> {where(request_status:1)}
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  scope :owner, -> { where(status:1) }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, :password, presence: true
    validates :password, confirmation: true
    has_many :messages, dependent: :destroy
    has_many :chat_rooms, through: :room_users
    has_many :room_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    before_action :is_authenticated, except: [:sign_in, :post_sign_in, :new, :create]
    before_action :not_loggedin, only: [:sign_in, :post_sign_in, :new, :create]
    before_action :pending_requests, except: [:sign_in, :post_sign_in, :new, :create]

    private
    def is_authenticated
        unless loggedin?
            flash[:alert] = "You should be logged-in to use this service"
            redirect_to sign_in_path
        end
    end

    def not_loggedin
        if loggedin?
            flash[:alert] = "You are already logged-in"
            redirect_to root_path
        end
    end

    def pending_requests
        requests = Request.pending.where(owner_id:current_user.id)
        rooms = []
        requests.each do |req|
            rooms.push(req.room_id)
        end
        @no_of_requests = rooms.length
    end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  skip_before_action :not_loggedin
  before_action :set_chat_room, only: [:show, :destroy, :join_room]
  before_action :is_authenticated

  def index
    room_user = RoomUser.owner.where.not(user_id:current_user.id).distinct.pluck(:chat_room_id)
    @chat_rooms = ChatRoom.where(id: room_user)
  end

  def new
    @chat_room = ChatRoom.new()
  end

  def create
    @chat_room = ChatRoom.new(name: params[:chat_room][:name])
    if @chat_room.save
      @room_user = @chat_room.room_users.new()
      @room_user.user_id = current_user.id
      @room_user.status = 1
      @room_user.save
      redirect_to root_path
    end
  end
  
  def join_room
    owner = RoomUser.owner.find_by(chat_room_id:@chat_room.id)
    r = Request.new(room_id:@chat_room.id, user_id:current_user.id, request_status:0, owner_id:owner.user_id)
    if r.save
      redirect_to root_path
    end
  end

  def owner
    requests = Request.pending.where(owner_id:current_user.id).pluck(:room_id)
    @chat_rooms = ChatRoom.where(id: requests)
  end

  def see_request
    @requests = Request.pending.where(owner_id:current_user.id).where(room_id:params[:chat_room_id])
  end

  def accept_request
    request = Request.pending.where(owner_id:current_user.id).where(room_id:params[:chat_room_id]).find_by(user_id:params[:requester_id])
    request.request_status = 1
    request.save
    room_user = RoomUser.new(user_id:params[:requester_id], chat_room_id:params[:chat_room_id], status:0)
    if room_user.save 
      redirect_to root_path
    end
    # binding.pry
  end

  def reject_request
    request = Request.pending.where(owner_id:current_user.id).where(room_id:params[:chat_room_id]).find_by(user_id:params[:requester_id])
    request.destroy
    redirect_to root_path
  end

  private
  def set_chat_room
    @chat_room = ChatRoom.find(params[:chat_room_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

    def chatroom
        @all_messages = Message.where(chat_room_id:params[:room_id])
        @message = current_user.messages.new()
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    skip_before_action :not_loggedin

    def create
        @message = current_user.messages.new(message_params)
        @message.chat_room_id = params[:message][:chat_room_id]
        if @message.save
            ActionCable.server.broadcast "chatroom_channel_#{params[:message][:chat_room_id]}", 
                {message: all_message_partial_render(@message)}
        else
            @all_messages = Message.all
            render :"homes/chatroom", status: :unprocessable_entity
        end
    end

    private
    def message_params
        params.require(:message).permit(:body, :chat_room_id)
    end

    def all_message_partial_render(message)
        render(partial:'message', locals: {message: message})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def sign_in
    end

    def post_sign_in
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            log_in(@user)
            redirect_to root_path
        else
            flash[:alert] = "Invalid Credentials!!"
            render :sign_in, status: :unprocessable_entity
        end
    end

    def log_out
        logout
        redirect_to sign_in_path, status: :see_other 
    end

    private
    def not_loggedin
        if loggedin?
            flash[:alert] = "You are already logged-in"
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to root_path
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            current_user = User.find(session[:user_id])
        end
    end

    def loggedin?
        current_user.present?
    end

    def logout
        session[:user_id] = nil
    end
end

app/views/chat_rooms/index.html.erb
<% @chat_rooms.each do |chat_room| %>
  <%= chat_room.name %>
  <% if Request.pending.where(room_id: chat_room.id).find_by(user_id:current_user.id) %>
    <p class="link-primary">Pending</p>
  <% elsif Request.accepted.where(room_id: chat_room.id).find_by(user_id:current_user.id) %>
    <%= link_to "Enter",chatroom_path(chat_room) %>
  <% else %>
    <%= link_to "Join",join_room_path(chat_room) %>
  <% end %> 
<% end %>

app/views/chat_rooms/new.html.erb
<%= form_with model: @chat_room do |f|  %>
  <%= f.label :Name %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/chat_rooms/owner.html.erb
<% @chat_rooms.each do |room| %>
  <div>
    <%= room.name %> 
    <%= link_to "See-All",see_requests_path(room) %>
  </div>
<% end %>

app/views/chat_rooms/see_request.html.erb
<% @requests.each do |req| %>
  <h5> Requested by :- <%= User.find(req.user_id).username %> </h5>
  <%= button_to "Accept",accept_request_path(req.room_id, req.user_id), class:"btn btn-success", method: :get %>
  <%= button_to "Reject",reject_request_path(req.room_id, req.user_id), class:"btn btn-danger", method: :get %>
  <br>
<% end %>

app/views/homes/_all_messages.html.erb
<% if !all_messages.nil? %>
    <% all_messages.each do |message| %>
        <h6> <%= message.user.username %> : <%= message.body %> </h6>
    <% end %>
<% else %>
    <h6> <%= message.user.username %> : <%= message.body %> </h6>
<% end %>

app/views/homes/chatroom.html.erb
<div class="card">
    <% if @all_messages %>
            <div id="message-container">
            <%= render @all_messages %>
            </div>
    <% end %>

    <%= form_with(model:@message, url: new_message_path) do |f| %>
        <% if @message.errors.any? %>
            <% @message.errors.each do |e| %>
                <%= e.full_message %>
            <% end %>
        <% end %>
            <%= f.label :Body %>
            <%= f.text_field :body %>
            <%= f.hidden_field :chat_room_id, value:params[:room_id], id:'chat_room_id' %>
            <%= f.submit "send" %>

    <% end %>
</div>

<%= link_to "Log-out",logout_path, data: { turbo_method: :delete } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% if flash[:alert] %>
      <p class="alert alert-danger"> <%= flash[:alert] %> </p>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_message.html.erb
<h6><%= message.user.username %> : <%= message.body %></h6>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Home",root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Create Room", new_chat_room_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Join Room", chat_rooms_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <% if @no_of_requests.present? %>
          <% if @no_of_requests > 0 %>
            <%= link_to "Requests".html_safe + "(" + "<span class='badge badge-pill text-danger'>".html_safe + "#{@no_of_requests}" + "</span>".html_safe + ")", owner_path, class:"nav-link" %>
          <% else %>
            <%= link_to "Requests", owner_path, class:"nav-link" %>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/new.html.erb
<%= form_with model:@user do |f| %>
    
    <div>
        <%= f.label :username %>
        <%= f.text_field :username %>
    </div>

    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>

    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>

    <div>
        <%= f.submit "Create New user" %>
    </div>

<% end %>